authors:
  tomjarle:
    name: Tom Jarle Christiansen
    description: Potet
    avatar: https://github.com/fuzzbin.png

  matthias:
    name: Matthias Veel Krauss
    description: Potetmos
    avatar: https://github.com/mn3m.png
